alter table if exists public.profiles enable row level security;
alter table if exists public.missions enable row level security;
alter table public.profiles add column if not exists first_name text;
alter table public.profiles add column if not exists last_name text;
alter table public.profiles add column if not exists company_name text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists vehicle_category text;
alter table public.profiles add column if not exists vehicle_brand text;
alter table public.profiles add column if not exists plate_number text;
alter table public.profiles add column if not exists role text default 'driver';
alter table public.profiles add column if not exists is_admin boolean default false;
alter table public.profiles add column if not exists latitude double precision;
alter table public.profiles add column if not exists longitude double precision;
alter table public.profiles add column if not exists last_location_at timestamptz;
alter table public.missions add column if not exists reference text;
alter table public.missions add column if not exists do_user_id uuid;
alter table public.missions add column if not exists driver_user_id uuid;
alter table public.missions add column if not exists client_first_name text;
alter table public.missions add column if not exists client_last_name text;
alter table public.missions add column if not exists passenger_count integer default 1;
alter table public.missions add column if not exists luggage_count integer default 0;
alter table public.missions add column if not exists pickup_address text;
alter table public.missions add column if not exists destination_address text;
alter table public.missions add column if not exists pickup_datetime timestamptz;
alter table public.missions add column if not exists payment_mode text;
alter table public.missions add column if not exists fare_amount numeric default 0;
alter table public.missions add column if not exists do_commission_type text default 'fixed';
alter table public.missions add column if not exists do_commission_value numeric default 0;
alter table public.missions add column if not exists do_commission_amount numeric default 0;
alter table public.missions add column if not exists relaivtc_fee numeric default 0;
alter table public.missions add column if not exists global_commission_amount numeric default 0;
alter table public.missions add column if not exists driver_net_amount numeric default 0;
alter table public.missions add column if not exists vehicle_category text;
alter table public.missions add column if not exists is_mise_a_disposition boolean default false;
alter table public.missions add column if not exists mise_a_disposition_hours integer;
alter table public.missions add column if not exists status text default 'broadcasted';
alter table public.missions add column if not exists archived boolean default false;
alter table public.missions add column if not exists started_at timestamptz;
alter table public.missions add column if not exists arrived_at timestamptz;
alter table public.missions add column if not exists onboard_at timestamptz;
alter table public.missions add column if not exists completed_at timestamptz;
alter table public.missions add column if not exists created_at timestamptz default now();
create or replace function public.set_mission_reference() returns trigger language plpgsql as $$ begin if new.reference is null or new.reference = '' then new.reference := 'RLV-' || to_char(now(),'YYYYMMDD') || '-' || lpad((floor(random()*9000)+1000)::text,4,'0'); end if; return new; end; $$;
drop trigger if exists trg_reference on public.missions;
create trigger trg_reference before insert on public.missions for each row execute function public.set_mission_reference();
create or replace function public.compute_mission_amounts() returns trigger language plpgsql as $$ declare relai numeric := 1; do_comm numeric := 0; begin if coalesce(new.fare_amount,0) > 400 then relai := 5; elsif coalesce(new.fare_amount,0) > 200 then relai := 3; elsif coalesce(new.fare_amount,0) > 100 then relai := 2; else relai := 1; end if; if coalesce(new.do_commission_type,'fixed') = 'percentage' then do_comm := coalesce(new.fare_amount,0) * coalesce(new.do_commission_value,0) / 100.0; else do_comm := coalesce(new.do_commission_value,0); end if; new.do_commission_amount := do_comm; new.relaivtc_fee := relai; new.global_commission_amount := do_comm + relai; new.driver_net_amount := greatest(coalesce(new.fare_amount,0) - (do_comm + relai), 0); return new; end; $$;
drop trigger if exists trg_compute on public.missions;
create trigger trg_compute before insert or update on public.missions for each row execute function public.compute_mission_amounts();
drop function if exists public.accept_mission(uuid);
create function public.accept_mission(p_id uuid) returns void language plpgsql security definer as $$ begin update public.missions set driver_user_id = auth.uid(), status = 'accepted' where id = p_id and archived = false and driver_user_id is null and status in ('new','broadcasted'); end; $$;
drop function if exists public.reject_driver(uuid);
create function public.reject_driver(p_id uuid) returns void language plpgsql security definer as $$ begin update public.missions set driver_user_id = null, status = 'broadcasted' where id = p_id; end; $$;
drop function if exists public.update_status(uuid,text);
create function public.update_status(p_id uuid, p_status text) returns void language plpgsql security definer as $$ begin update public.missions set status = p_status, started_at = case when p_status='en_route' then now() else started_at end, arrived_at = case when p_status='sur_place' then now() else arrived_at end, onboard_at = case when p_status='client_a_bord' then now() else onboard_at end, completed_at = case when p_status='completed' then now() else completed_at end where id = p_id; end; $$;
drop function if exists public.update_driver_location(double precision,double precision);
create function public.update_driver_location(p_lat double precision, p_lng double precision) returns void language plpgsql security definer as $$ begin update public.profiles set latitude = p_lat, longitude = p_lng, last_location_at = now() where id = auth.uid(); end; $$;
drop policy if exists all_profiles on public.profiles;
create policy all_profiles on public.profiles for all using (true) with check (true);
drop policy if exists all_missions on public.missions;
create policy all_missions on public.missions for all using (true) with check (true);
select 'RELAIVTC V5.1 OK' as status;
